##
## EPITECH PROJECT, 2025
## makefile
## File description:
## makefile
##

SRC	=	*.cpp

NAME	=	MyCat

all:	$(NAME)

$(NAME):
	g++ -o $(NAME) $(SRC) -Wall -Wextra

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(OBJ)
	rm -f *~
	rm -f *#
	rm -f coding-style-reports.log
	rm -f $(NAME)